// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(eightviewsFFI)
import eightviewsFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_eightviews_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_eightviews_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureEightviewsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct ArchiveEntryRecord {
    /**
     * Zero-based position of this entry after natural sort.
     */
    public var index: UInt32
    /**
     * Filename as decoded from the archive (UTF-8, lossy where necessary).
     */
    public var filename: String
    /**
     * Uncompressed size of the entry in bytes; 0 for directories or unknown.
     */
    public var sizeBytes: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Zero-based position of this entry after natural sort.
         */index: UInt32, 
        /**
         * Filename as decoded from the archive (UTF-8, lossy where necessary).
         */filename: String, 
        /**
         * Uncompressed size of the entry in bytes; 0 for directories or unknown.
         */sizeBytes: UInt64) {
        self.index = index
        self.filename = filename
        self.sizeBytes = sizeBytes
    }
}

#if compiler(>=6)
extension ArchiveEntryRecord: Sendable {}
#endif


extension ArchiveEntryRecord: Equatable, Hashable {
    public static func ==(lhs: ArchiveEntryRecord, rhs: ArchiveEntryRecord) -> Bool {
        if lhs.index != rhs.index {
            return false
        }
        if lhs.filename != rhs.filename {
            return false
        }
        if lhs.sizeBytes != rhs.sizeBytes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(index)
        hasher.combine(filename)
        hasher.combine(sizeBytes)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeArchiveEntryRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ArchiveEntryRecord {
        return
            try ArchiveEntryRecord(
                index: FfiConverterUInt32.read(from: &buf), 
                filename: FfiConverterString.read(from: &buf), 
                sizeBytes: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: ArchiveEntryRecord, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.index, into: &buf)
        FfiConverterString.write(value.filename, into: &buf)
        FfiConverterUInt64.write(value.sizeBytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArchiveEntryRecord_lift(_ buf: RustBuffer) throws -> ArchiveEntryRecord {
    return try FfiConverterTypeArchiveEntryRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArchiveEntryRecord_lower(_ value: ArchiveEntryRecord) -> RustBuffer {
    return FfiConverterTypeArchiveEntryRecord.lower(value)
}


public struct OcrSearchResult {
    /**
     * Path to the archive that contains the matching page.
     */
    public var archivePath: String
    /**
     * Zero-based index of the matching page within the archive.
     */
    public var pageIndex: UInt32
    /**
     * Short excerpt with surrounding context; matched terms wrapped in <b>…</b>.
     */
    public var snippet: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Path to the archive that contains the matching page.
         */archivePath: String, 
        /**
         * Zero-based index of the matching page within the archive.
         */pageIndex: UInt32, 
        /**
         * Short excerpt with surrounding context; matched terms wrapped in <b>…</b>.
         */snippet: String) {
        self.archivePath = archivePath
        self.pageIndex = pageIndex
        self.snippet = snippet
    }
}

#if compiler(>=6)
extension OcrSearchResult: Sendable {}
#endif


extension OcrSearchResult: Equatable, Hashable {
    public static func ==(lhs: OcrSearchResult, rhs: OcrSearchResult) -> Bool {
        if lhs.archivePath != rhs.archivePath {
            return false
        }
        if lhs.pageIndex != rhs.pageIndex {
            return false
        }
        if lhs.snippet != rhs.snippet {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(archivePath)
        hasher.combine(pageIndex)
        hasher.combine(snippet)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOcrSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OcrSearchResult {
        return
            try OcrSearchResult(
                archivePath: FfiConverterString.read(from: &buf), 
                pageIndex: FfiConverterUInt32.read(from: &buf), 
                snippet: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: OcrSearchResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.archivePath, into: &buf)
        FfiConverterUInt32.write(value.pageIndex, into: &buf)
        FfiConverterString.write(value.snippet, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOcrSearchResult_lift(_ buf: RustBuffer) throws -> OcrSearchResult {
    return try FfiConverterTypeOcrSearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOcrSearchResult_lower(_ value: OcrSearchResult) -> RustBuffer {
    return FfiConverterTypeOcrSearchResult.lower(value)
}


public struct SessionStateRecord {
    /**
     * Zero-based index of the last viewed page.
     */
    public var pageIndex: UInt32
    /**
     * Zoom multiplier; 1.0 = 100 %.
     */
    public var zoomLevel: Double
    /**
     * Clockwise rotation in degrees.  Valid values: 0, 90, 180, 270.
     */
    public var rotationDegrees: Int32
    /**
     * Whether two consecutive pages are shown side-by-side.
     */
    public var twoPageSpread: Bool
    /**
     * Reading direction; true = right-to-left (manga layout).
     */
    public var rightToLeft: Bool
    /**
     * Scaling mode: 0 = original size, 1 = fit window, 2 = fit width.
     */
    public var scaleMode: Int32
    /**
     * Horizontal scroll offset (window coordinates).
     */
    public var scrollX: Double
    /**
     * Vertical scroll offset (window coordinates).
     */
    public var scrollY: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Zero-based index of the last viewed page.
         */pageIndex: UInt32, 
        /**
         * Zoom multiplier; 1.0 = 100 %.
         */zoomLevel: Double, 
        /**
         * Clockwise rotation in degrees.  Valid values: 0, 90, 180, 270.
         */rotationDegrees: Int32, 
        /**
         * Whether two consecutive pages are shown side-by-side.
         */twoPageSpread: Bool, 
        /**
         * Reading direction; true = right-to-left (manga layout).
         */rightToLeft: Bool, 
        /**
         * Scaling mode: 0 = original size, 1 = fit window, 2 = fit width.
         */scaleMode: Int32, 
        /**
         * Horizontal scroll offset (window coordinates).
         */scrollX: Double, 
        /**
         * Vertical scroll offset (window coordinates).
         */scrollY: Double) {
        self.pageIndex = pageIndex
        self.zoomLevel = zoomLevel
        self.rotationDegrees = rotationDegrees
        self.twoPageSpread = twoPageSpread
        self.rightToLeft = rightToLeft
        self.scaleMode = scaleMode
        self.scrollX = scrollX
        self.scrollY = scrollY
    }
}

#if compiler(>=6)
extension SessionStateRecord: Sendable {}
#endif


extension SessionStateRecord: Equatable, Hashable {
    public static func ==(lhs: SessionStateRecord, rhs: SessionStateRecord) -> Bool {
        if lhs.pageIndex != rhs.pageIndex {
            return false
        }
        if lhs.zoomLevel != rhs.zoomLevel {
            return false
        }
        if lhs.rotationDegrees != rhs.rotationDegrees {
            return false
        }
        if lhs.twoPageSpread != rhs.twoPageSpread {
            return false
        }
        if lhs.rightToLeft != rhs.rightToLeft {
            return false
        }
        if lhs.scaleMode != rhs.scaleMode {
            return false
        }
        if lhs.scrollX != rhs.scrollX {
            return false
        }
        if lhs.scrollY != rhs.scrollY {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pageIndex)
        hasher.combine(zoomLevel)
        hasher.combine(rotationDegrees)
        hasher.combine(twoPageSpread)
        hasher.combine(rightToLeft)
        hasher.combine(scaleMode)
        hasher.combine(scrollX)
        hasher.combine(scrollY)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionStateRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionStateRecord {
        return
            try SessionStateRecord(
                pageIndex: FfiConverterUInt32.read(from: &buf), 
                zoomLevel: FfiConverterDouble.read(from: &buf), 
                rotationDegrees: FfiConverterInt32.read(from: &buf), 
                twoPageSpread: FfiConverterBool.read(from: &buf), 
                rightToLeft: FfiConverterBool.read(from: &buf), 
                scaleMode: FfiConverterInt32.read(from: &buf), 
                scrollX: FfiConverterDouble.read(from: &buf), 
                scrollY: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: SessionStateRecord, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.pageIndex, into: &buf)
        FfiConverterDouble.write(value.zoomLevel, into: &buf)
        FfiConverterInt32.write(value.rotationDegrees, into: &buf)
        FfiConverterBool.write(value.twoPageSpread, into: &buf)
        FfiConverterBool.write(value.rightToLeft, into: &buf)
        FfiConverterInt32.write(value.scaleMode, into: &buf)
        FfiConverterDouble.write(value.scrollX, into: &buf)
        FfiConverterDouble.write(value.scrollY, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionStateRecord_lift(_ buf: RustBuffer) throws -> SessionStateRecord {
    return try FfiConverterTypeSessionStateRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionStateRecord_lower(_ value: SessionStateRecord) -> RustBuffer {
    return FfiConverterTypeSessionStateRecord.lower(value)
}


public struct ThumbnailRecord {
    /**
     * Page index (zero-based, matches ArchiveEntryRecord.index).
     */
    public var index: UInt32
    /**
     * Thumbnail image as raw RGBA bytes (width × height × 4).
     */
    public var rgbaBytes: Data
    /**
     * Width of the thumbnail in pixels.
     */
    public var width: UInt32
    /**
     * Height of the thumbnail in pixels.
     */
    public var height: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Page index (zero-based, matches ArchiveEntryRecord.index).
         */index: UInt32, 
        /**
         * Thumbnail image as raw RGBA bytes (width × height × 4).
         */rgbaBytes: Data, 
        /**
         * Width of the thumbnail in pixels.
         */width: UInt32, 
        /**
         * Height of the thumbnail in pixels.
         */height: UInt32) {
        self.index = index
        self.rgbaBytes = rgbaBytes
        self.width = width
        self.height = height
    }
}

#if compiler(>=6)
extension ThumbnailRecord: Sendable {}
#endif


extension ThumbnailRecord: Equatable, Hashable {
    public static func ==(lhs: ThumbnailRecord, rhs: ThumbnailRecord) -> Bool {
        if lhs.index != rhs.index {
            return false
        }
        if lhs.rgbaBytes != rhs.rgbaBytes {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(index)
        hasher.combine(rgbaBytes)
        hasher.combine(width)
        hasher.combine(height)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeThumbnailRecord: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ThumbnailRecord {
        return
            try ThumbnailRecord(
                index: FfiConverterUInt32.read(from: &buf), 
                rgbaBytes: FfiConverterData.read(from: &buf), 
                width: FfiConverterUInt32.read(from: &buf), 
                height: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: ThumbnailRecord, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.index, into: &buf)
        FfiConverterData.write(value.rgbaBytes, into: &buf)
        FfiConverterUInt32.write(value.width, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThumbnailRecord_lift(_ buf: RustBuffer) throws -> ThumbnailRecord {
    return try FfiConverterTypeThumbnailRecord.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThumbnailRecord_lower(_ value: ThumbnailRecord) -> RustBuffer {
    return FfiConverterTypeThumbnailRecord.lower(value)
}


public enum ScError: Swift.Error {

    
    
    case Archive(message: String)
    
    case Image(message: String)
    
    case Storage(message: String)
    
    case Io(message: String)
    
    case UnsupportedFormat(message: String)
    
    case EntryNotFound(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeScError: FfiConverterRustBuffer {
    typealias SwiftType = ScError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ScError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Archive(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Image(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Storage(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .Io(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .UnsupportedFormat(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .EntryNotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ScError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Archive(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Image(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Storage(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .Io(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .UnsupportedFormat(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .EntryNotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScError_lift(_ buf: RustBuffer) throws -> ScError {
    return try FfiConverterTypeScError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeScError_lower(_ value: ScError) -> RustBuffer {
    return FfiConverterTypeScError.lower(value)
}


extension ScError: Equatable, Hashable {}




extension ScError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeArchiveEntryRecord: FfiConverterRustBuffer {
    typealias SwiftType = [ArchiveEntryRecord]

    public static func write(_ value: [ArchiveEntryRecord], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeArchiveEntryRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ArchiveEntryRecord] {
        let len: Int32 = try readInt(&buf)
        var seq = [ArchiveEntryRecord]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeArchiveEntryRecord.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeOcrSearchResult: FfiConverterRustBuffer {
    typealias SwiftType = [OcrSearchResult]

    public static func write(_ value: [OcrSearchResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeOcrSearchResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [OcrSearchResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [OcrSearchResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeOcrSearchResult.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeThumbnailRecord: FfiConverterRustBuffer {
    typealias SwiftType = [ThumbnailRecord]

    public static func write(_ value: [ThumbnailRecord], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeThumbnailRecord.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ThumbnailRecord] {
        let len: Int32 = try readInt(&buf)
        var seq = [ThumbnailRecord]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeThumbnailRecord.read(from: &buf))
        }
        return seq
    }
}
/**
 * Return true if the file at `archive_path` is a supported archive.
 *
 * Checks the file extension first; falls back to magic-byte detection for
 * unknown extensions.  Directories always return true.
 */
public func archiveIsSupported(archivePath: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_eightviews_fn_func_archive_is_supported(
        FfiConverterString.lower(archivePath),$0
    )
})
}
/**
 * List all image pages in an archive, sorted in natural order.
 *
 * Supported formats: ZIP/CBZ, TAR (plain/gz/bz2/xz), 7z, RAR/CBR, directory.
 */
public func archiveListPages(archivePath: String)throws  -> [ArchiveEntryRecord]  {
    return try  FfiConverterSequenceTypeArchiveEntryRecord.lift(try rustCallWithError(FfiConverterTypeScError_lift) {
    uniffi_eightviews_fn_func_archive_list_pages(
        FfiConverterString.lower(archivePath),$0
    )
})
}
/**
 * Read raw bytes for the first image in an archive (QuickLook thumbnail path).
 *
 * Uses the optimised partial-read path from sc_archive::read_first_image,
 * which avoids decompressing the entire archive.
 */
public func archiveReadFirstImage(archivePath: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeScError_lift) {
    uniffi_eightviews_fn_func_archive_read_first_image(
        FfiConverterString.lower(archivePath),$0
    )
})
}
/**
 * Read raw image bytes for a single page by zero-based index.
 *
 * The bytes are the compressed image as stored in the archive (JPEG, PNG,
 * WebP, …).  Callers are responsible for decoding and rendering.
 */
public func archiveReadPage(archivePath: String, index: UInt32)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeScError_lift) {
    uniffi_eightviews_fn_func_archive_read_page(
        FfiConverterString.lower(archivePath),
        FfiConverterUInt32.lower(index),$0
    )
})
}
/**
 * Generate thumbnails for all pages of an archive in parallel.
 *
 * Returns one ThumbnailRecord per page, sorted by page index.
 * Pages that fail to decode are silently skipped.
 */
public func generateArchiveThumbnails(archivePath: String, thumbSize: UInt32)throws  -> [ThumbnailRecord]  {
    return try  FfiConverterSequenceTypeThumbnailRecord.lift(try rustCallWithError(FfiConverterTypeScError_lift) {
    uniffi_eightviews_fn_func_generate_archive_thumbnails(
        FfiConverterString.lower(archivePath),
        FfiConverterUInt32.lower(thumbSize),$0
    )
})
}
/**
 * Generate a thumbnail for a single page's raw image bytes.
 *
 * Returns the thumbnail as raw RGBA bytes (width × height × 4).
 * `thumb_size` is the maximum edge length (thumbnail is fit within a square).
 */
public func generateThumbnail(imageBytes: Data, thumbSize: UInt32)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeScError_lift) {
    uniffi_eightviews_fn_func_generate_thumbnail(
        FfiConverterData.lower(imageBytes),
        FfiConverterUInt32.lower(thumbSize),$0
    )
})
}
/**
 * Search cached OCR text within a single archive.
 *
 * Results are ordered by page index.  Returns an empty list for empty queries
 * or archives with no cached OCR data.
 */
public func ocrSearch(archivePath: String, query: String)throws  -> [OcrSearchResult]  {
    return try  FfiConverterSequenceTypeOcrSearchResult.lift(try rustCallWithError(FfiConverterTypeScError_lift) {
    uniffi_eightviews_fn_func_ocr_search(
        FfiConverterString.lower(archivePath),
        FfiConverterString.lower(query),$0
    )
})
}
/**
 * Return the library version string (SemVer, e.g. "0.1.0").
 */
public func scLibraryVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_eightviews_fn_func_sc_library_version($0
    )
})
}
/**
 * Delete the session record for an archive (e.g. on archive removal).
 *
 * No-op if no record exists; never throws.
 */
public func sessionDelete(archivePath: String)  {try! rustCall() {
    uniffi_eightviews_fn_func_session_delete(
        FfiConverterString.lower(archivePath),$0
    )
}
}
/**
 * Load persisted session state for an archive.
 *
 * Returns default state (page 0, zoom 1.0, no rotation, fit-window) when
 * no record exists for the given archive_path.
 */
public func sessionLoad(archivePath: String)throws  -> SessionStateRecord  {
    return try  FfiConverterTypeSessionStateRecord_lift(try rustCallWithError(FfiConverterTypeScError_lift) {
    uniffi_eightviews_fn_func_session_load(
        FfiConverterString.lower(archivePath),$0
    )
})
}
/**
 * Persist session state for an archive, creating or replacing the record.
 */
public func sessionSave(archivePath: String, state: SessionStateRecord)throws   {try rustCallWithError(FfiConverterTypeScError_lift) {
    uniffi_eightviews_fn_func_session_save(
        FfiConverterString.lower(archivePath),
        FfiConverterTypeSessionStateRecord_lower(state),$0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_eightviews_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_eightviews_checksum_func_archive_is_supported() != 20066) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eightviews_checksum_func_archive_list_pages() != 54808) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eightviews_checksum_func_archive_read_first_image() != 62461) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eightviews_checksum_func_archive_read_page() != 16220) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eightviews_checksum_func_generate_archive_thumbnails() != 63533) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eightviews_checksum_func_generate_thumbnail() != 48397) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eightviews_checksum_func_ocr_search() != 1788) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eightviews_checksum_func_sc_library_version() != 37413) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eightviews_checksum_func_session_delete() != 2994) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eightviews_checksum_func_session_load() != 30142) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_eightviews_checksum_func_session_save() != 60005) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureEightviewsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all