// uniffi scaffolding generated from src/simplecomic.udl
uniffi::include_scaffolding!("simplecomic");

use thiserror::Error;

// ── Record types (UDL `dictionary` mapping) ───────────────────────────────────

// In the UDL workflow, scaffolding generated by build.rs already applies the
// udl_derive(Record) attribute; adding #[derive(uniffi::Record)] here would
// duplicate trait impls and cause E0119.  Plain derives only.
#[derive(Debug, Clone)]
pub struct ArchiveEntryRecord {
    pub index: u32,
    pub filename: String,
    pub size_bytes: u64,
}

#[derive(Debug, Clone)]
pub struct SessionStateRecord {
    pub page_index: u32,
    pub zoom_level: f64,
    pub rotation_degrees: i32,
    pub two_page_spread: bool,
    pub right_to_left: bool,
    pub scale_mode: i32,
    pub scroll_x: f64,
    pub scroll_y: f64,
}

#[derive(Debug, Clone)]
pub struct ThumbnailRecord {
    pub index: u32,
    pub rgba_bytes: Vec<u8>,
    pub width: u32,
    pub height: u32,
}

// ── Error type (UDL `[Error] enum` mapping) ──────────────────────────────────
// Flat enum: no associated data on any variant; uniffi exposes the Display
// message as the Swift error description.
// The udl_derive(Error) attribute is applied by the scaffolding; no
// #[derive(uniffi::Error)] needed here.

#[derive(Debug, Error)]
pub enum ScError {
    #[error("archive error")]
    Archive,
    #[error("image error")]
    Image,
    #[error("storage error")]
    Storage,
    #[error("I/O error")]
    Io,
    #[error("unsupported format")]
    UnsupportedFormat,
    #[error("entry not found")]
    EntryNotFound,
}

impl From<anyhow::Error> for ScError {
    fn from(e: anyhow::Error) -> Self {
        let msg = e.to_string();
        if msg.contains("unsupported format") || msg.contains("unknown magic") {
            ScError::UnsupportedFormat
        } else if msg.contains("not found")
            || msg.contains("out of range")
            || msg.contains("no image")
        {
            ScError::EntryNotFound
        } else {
            ScError::Archive
        }
    }
}

// ── C smoke-test export ───────────────────────────────────────────────────────

/// Returns the library version as a C string.
///
/// # Safety
///
/// The returned pointer is valid for the lifetime of the process; callers must
/// not free it.
#[no_mangle]
pub extern "C" fn sc_version() -> *const std::ffi::c_char {
    c"0.1.0".as_ptr()
}

// ── ScPageList opaque handle — open-once enumeration ─────────────────────────

/// Opaque type returned by `sc_archive_open_pages`.
///
/// Holds all page-metadata from a single archive open.  The archive is opened
/// and fully indexed once; callers query entries without re-opening.
/// `filenames` are NUL-terminated `CString` values parallel to `entries`;
/// pointers returned by `sc_page_list_name` are valid until `sc_archive_pages_free`.
pub struct ScPageList {
    entries: Vec<sc_archive::ArchiveEntry>,
    /// NUL-terminated filename for each entry, kept alive for `sc_page_list_name`.
    filenames: Vec<std::ffi::CString>,
}

/// C-callable: open an archive and collect all page-metadata in one shot.
///
/// Returns an opaque `ScPageList *` on success.  Caller must release it with
/// `sc_archive_pages_free`.  Returns NULL on error and sets `*error_code_out`:
///   1 = I/O / open error
///   3 = unsupported format
///
/// # Safety
/// `archive_path` must be a valid NUL-terminated UTF-8 C string.
#[no_mangle]
pub unsafe extern "C" fn sc_archive_open_pages(
    archive_path: *const std::ffi::c_char,
    error_code_out: *mut i32,
) -> *mut ScPageList {
    let set_err = |code: i32| {
        if !error_code_out.is_null() {
            *error_code_out = code;
        }
    };
    if archive_path.is_null() {
        set_err(1);
        return std::ptr::null_mut();
    }
    let path_str = match std::ffi::CStr::from_ptr(archive_path).to_str() {
        Ok(s) => s,
        Err(_) => { set_err(1); return std::ptr::null_mut(); }
    };
    let archive = match sc_archive::open_archive(std::path::Path::new(path_str)) {
        Ok(a) => a,
        Err(e) => {
            let msg = e.to_string();
            set_err(if msg.contains("unsupported") { 3 } else { 1 });
            return std::ptr::null_mut();
        }
    };
    let entries = archive.entries().to_vec();
    let filenames = entries
        .iter()
        .map(|e| std::ffi::CString::new(e.filename.as_bytes()).unwrap_or_default())
        .collect();
    set_err(0);
    Box::into_raw(Box::new(ScPageList { entries, filenames }))
}

/// Return the number of pages in `list`.
///
/// # Safety
/// `list` must be a non-null pointer returned by `sc_archive_open_pages`.
#[no_mangle]
pub unsafe extern "C" fn sc_page_list_count(list: *const ScPageList) -> u32 {
    (&(*list).entries).len() as u32
}

/// Return the NUL-terminated filename for entry `index` in `list`.
///
/// The returned pointer is valid until `sc_archive_pages_free` is called.
/// Do NOT free the pointer separately.  Returns NULL if `index` is out of range.
///
/// # Safety
/// `list` must be a valid non-null `ScPageList` pointer.
#[no_mangle]
pub unsafe extern "C" fn sc_page_list_name(
    list: *const ScPageList,
    index: u32,
) -> *const std::ffi::c_char {
    match (&(*list).filenames).get(index as usize) {
        Some(cs) => cs.as_ptr(),
        None => std::ptr::null(),
    }
}

/// Return the uncompressed byte-size of entry `index` in `list`.  Returns 0 if out of range.
///
/// # Safety
/// `list` must be a valid non-null `ScPageList` pointer.
#[no_mangle]
pub unsafe extern "C" fn sc_page_list_size(list: *const ScPageList, index: u32) -> u64 {
    match (&(*list).entries).get(index as usize) {
        Some(e) => e.size,
        None => 0,
    }
}

/// Free an `ScPageList` returned by `sc_archive_open_pages`.  NULL is safe.
///
/// # Safety
/// `list` must have been returned by `sc_archive_open_pages`.
#[no_mangle]
pub unsafe extern "C" fn sc_archive_pages_free(list: *mut ScPageList) {
    if !list.is_null() {
        drop(Box::from_raw(list));
    }
}

// ── Archive namespace functions (UDL `namespace simplecomic`) ─────────────────

pub fn archive_is_supported(archive_path: &str) -> bool {
    sc_archive::is_archive_supported(std::path::Path::new(archive_path))
}

/// C-callable: returns true if the NUL-terminated UTF-8 `path` is a supported archive.
///
/// # Safety
/// `path` must be a valid NUL-terminated C string. Null pointer returns false.
#[no_mangle]
pub unsafe extern "C" fn sc_archive_is_supported(path: *const std::ffi::c_char) -> bool {
    if path.is_null() {
        return false;
    }
    let s = match std::ffi::CStr::from_ptr(path).to_str() {
        Ok(s) => s,
        Err(_) => return false,
    };
    sc_archive::is_archive_supported(std::path::Path::new(s))
}

/// C-callable: read raw image bytes for page `index` from the archive at `archive_path`.
///
/// On success: returns a heap-allocated buffer; writes byte count to `*out_len`; sets
/// `*error_code_out` to 0.  The caller must release the buffer with `sc_free_bytes()`.
/// On failure: returns NULL; sets `*error_code_out` to a non-zero code:
///   1 = I/O / archive open error
///   2 = entry not found (index out of range)
///   3 = unsupported format
///
/// # Safety
/// `archive_path` must be a valid NUL-terminated UTF-8 C string.
/// `out_len` must be a valid non-null pointer; receives the allocation length that
/// must be passed verbatim to `sc_free_bytes`.
/// `error_code_out` may be null (error code is discarded).
#[no_mangle]
pub unsafe extern "C" fn sc_archive_read_page(
    archive_path: *const std::ffi::c_char,
    index: u32,
    out_len: *mut usize,
    error_code_out: *mut i32,
) -> *mut u8 {
    let set_err = |code: i32| {
        if !error_code_out.is_null() {
            *error_code_out = code;
        }
    };

    if archive_path.is_null() || out_len.is_null() {
        set_err(1);
        return std::ptr::null_mut();
    }
    let path_str = match std::ffi::CStr::from_ptr(archive_path).to_str() {
        Ok(s) => s,
        Err(_) => { set_err(1); return std::ptr::null_mut(); }
    };

    match archive_read_page(path_str, index) {
        Ok(bytes) => {
            let boxed: Box<[u8]> = bytes.into_boxed_slice();
            *out_len = boxed.len();
            set_err(0);
            Box::into_raw(boxed) as *mut u8
        }
        Err(ScError::EntryNotFound) => { set_err(2); std::ptr::null_mut() }
        Err(ScError::UnsupportedFormat) => { set_err(3); std::ptr::null_mut() }
        Err(_) => { set_err(1); std::ptr::null_mut() }
    }
}

/// C-callable: free a buffer returned by `sc_archive_read_page`.
///
/// # Safety
/// `ptr` must have been returned by `sc_archive_read_page` with the exact same `len`
/// value that was written to `*out_len` at call time.  Passing NULL is safe (no-op).
#[no_mangle]
pub unsafe extern "C" fn sc_free_bytes(ptr: *mut u8, len: usize) {
    if !ptr.is_null() {
        drop(Box::from_raw(std::slice::from_raw_parts_mut(ptr, len)));
    }
}

pub fn archive_list_pages(archive_path: &str) -> Result<Vec<ArchiveEntryRecord>, ScError> {
    let archive =
        sc_archive::open_archive(std::path::Path::new(archive_path)).map_err(ScError::from)?;
    let entries = archive
        .entries()
        .iter()
        .map(|e| ArchiveEntryRecord {
            index: e.index as u32,
            filename: e.filename.clone(),
            size_bytes: e.size,
        })
        .collect();
    Ok(entries)
}

pub fn archive_read_page(archive_path: &str, index: u32) -> Result<Vec<u8>, ScError> {
    let mut archive =
        sc_archive::open_archive(std::path::Path::new(archive_path)).map_err(ScError::from)?;
    let page_count = archive.entries().len();
    let idx = index as usize;
    if idx >= page_count {
        return Err(ScError::EntryNotFound);
    }
    archive.read_entry(idx).map_err(ScError::from)
}

pub fn archive_read_first_image(archive_path: &str) -> Result<Vec<u8>, ScError> {
    sc_archive::read_first_image(std::path::Path::new(archive_path)).map_err(ScError::from)
}

// ── Session namespace functions ───────────────────────────────────────────────

/// Open the session database.
///
/// In test builds uses an in-memory database so parallel tests do not contend
/// on the same file.  In production uses a file under the platform app-support directory:
/// - macOS: ~/Library/Application Support/SimpleComic/sessions.sqlite
/// - Linux: ~/.local/share/SimpleComic/sessions.sqlite
/// - Fallback: $TMPDIR/simplecomic_sessions.sqlite
#[cfg(not(test))]
fn open_session_db() -> Result<sc_storage::SessionManager, ScError> {
    let base = dirs::data_dir()
        .or_else(|| dirs::home_dir().map(|h| h.join(".local/share")))
        .unwrap_or_else(std::env::temp_dir);

    let app_dir = base.join("SimpleComic");
    if !app_dir.exists() {
        let _ = std::fs::create_dir_all(&app_dir);
    }

    let db_path = app_dir.join("sessions.sqlite");
    sc_storage::SessionManager::open(&db_path).map_err(|_| ScError::Storage)
}

#[cfg(test)]
fn open_session_db() -> Result<sc_storage::SessionManager, ScError> {
    sc_storage::SessionManager::open_in_memory().map_err(|_| ScError::Storage)
}

pub fn session_load(archive_path: &str) -> Result<SessionStateRecord, ScError> {
    let mgr = open_session_db()?;
    let state = mgr.load(archive_path).map_err(|_| ScError::Storage)?;
    Ok(state_to_record(state))
}

// UDL: void session_save([ByRef] string archive_path, SessionStateRecord state)
// → no [Throws] suppression: this function IS [Throws=ScError] in UDL, Result is correct.
pub fn session_save(archive_path: &str, state: SessionStateRecord) -> Result<(), ScError> {
    let mgr = open_session_db()?;
    mgr.save(archive_path, &record_to_state(state))
        .map_err(|_| ScError::Storage)
}

// UDL: void session_delete([ByRef] string archive_path)   — no [Throws], returns ()
pub fn session_delete(archive_path: &str) {
    if let Ok(mgr) = open_session_db() {
        let _ = mgr.delete(archive_path);
    }
}

pub fn sc_library_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

// ── Session C FFI ─────────────────────────────────────────────────────────────

/// C-compatible session state; mirrors SessionStateRecord.
/// All fields use fixed-width types safe for C struct layouts.
#[repr(C)]
pub struct ScSessionState {
    pub page_index: u32,
    pub zoom_level: f64,
    pub rotation_degrees: i32,
    pub two_page_spread: bool,
    pub right_to_left: bool,
    pub scale_mode: i32,
    pub scroll_x: f64,
    pub scroll_y: f64,
}

/// C-callable: load persisted session state for `archive_path`.
///
/// On success writes state to `*out_state` and returns true.
/// On failure (no record, DB error) writes default state and returns false.
/// archive_path must be a valid NUL-terminated UTF-8 C string.
/// out_state must be a valid non-null pointer.
///
/// # Safety
/// `archive_path` must be a valid NUL-terminated UTF-8 C string.
/// `out_state` must be a valid non-null pointer to a `ScSessionState`.
#[no_mangle]
pub unsafe extern "C" fn sc_session_load(
    archive_path: *const std::ffi::c_char,
    out_state: *mut ScSessionState,
) -> bool {
    if archive_path.is_null() || out_state.is_null() {
        return false;
    }
    let path_str = match std::ffi::CStr::from_ptr(archive_path).to_str() {
        Ok(s) => s,
        Err(_) => return false,
    };
    // Only return true if the DB actually has a record for this path.
    let mgr = match open_session_db() {
        Ok(m) => m,
        Err(_) => return false,
    };
    if !mgr.exists(path_str) {
        return false;
    }
    let state = match mgr.load(path_str) {
        Ok(s) => s,
        Err(_) => return false,
    };
    let rec = state_to_record(state);
    *out_state = ScSessionState {
        page_index: rec.page_index,
        zoom_level: rec.zoom_level,
        rotation_degrees: rec.rotation_degrees,
        two_page_spread: rec.two_page_spread,
        right_to_left: rec.right_to_left,
        scale_mode: rec.scale_mode,
        scroll_x: rec.scroll_x,
        scroll_y: rec.scroll_y,
    };
    true
}

/// C-callable: persist session state for `archive_path`.
///
/// Returns true on success, false on DB error.
///
/// # Safety
/// Both pointers must be valid NUL-terminated UTF-8 C strings / structs.
#[no_mangle]
pub unsafe extern "C" fn sc_session_save(
    archive_path: *const std::ffi::c_char,
    state: *const ScSessionState,
) -> bool {
    if archive_path.is_null() || state.is_null() {
        return false;
    }
    let path_str = match std::ffi::CStr::from_ptr(archive_path).to_str() {
        Ok(s) => s,
        Err(_) => return false,
    };
    let s = &*state;
    let rec = SessionStateRecord {
        page_index: s.page_index,
        zoom_level: s.zoom_level,
        rotation_degrees: s.rotation_degrees,
        two_page_spread: s.two_page_spread,
        right_to_left: s.right_to_left,
        scale_mode: s.scale_mode,
        scroll_x: s.scroll_x,
        scroll_y: s.scroll_y,
    };
    session_save(path_str, rec).is_ok()
}

/// C-callable: delete persisted session state for `archive_path`.  No-op if not found.
///
/// # Safety
/// `archive_path` must be a valid NUL-terminated UTF-8 C string.
#[no_mangle]
pub unsafe extern "C" fn sc_session_delete_c(archive_path: *const std::ffi::c_char) {
    if archive_path.is_null() {
        return;
    }
    if let Ok(path_str) = std::ffi::CStr::from_ptr(archive_path).to_str() {
        session_delete(path_str);
    }
}

// ── Thumbnail C FFI ──────────────────────────────────────────────────────────

/// C-callable: generate a thumbnail from raw image bytes.
///
/// `image_bytes[0..image_len]` — compressed image data (JPEG, PNG, WebP, …).
/// `thumb_size`                 — max dimension (width and height) of the output.
///
/// On success: writes RGBA dimensions to `*out_width` / `*out_height`, writes
/// byte count to `*out_len`, sets `*error_code_out` to 0, and returns a
/// heap-allocated RGBA buffer (4 bytes per pixel, row-major).
/// Caller must release with `sc_free_bytes(ptr, *out_len)`.
/// On failure: returns NULL and sets `*error_code_out` to 1.
///
/// # Safety
/// `image_bytes` must point to `image_len` valid bytes.
/// `out_len`, `out_width`, `out_height` must be valid non-null pointers.
/// `error_code_out` may be null.
#[no_mangle]
pub unsafe extern "C" fn sc_thumbnail_from_bytes(
    image_bytes: *const u8,
    image_len: usize,
    thumb_size: u32,
    out_len: *mut usize,
    out_width: *mut u32,
    out_height: *mut u32,
    error_code_out: *mut i32,
) -> *mut u8 {
    let set_err = |code: i32| {
        if !error_code_out.is_null() {
            *error_code_out = code;
        }
    };
    if image_bytes.is_null() || out_len.is_null() || out_width.is_null() || out_height.is_null() {
        set_err(1);
        return std::ptr::null_mut();
    }
    let bytes = std::slice::from_raw_parts(image_bytes, image_len);
    let img = match image::load_from_memory(bytes) {
        Ok(i) => i,
        Err(_) => { set_err(1); return std::ptr::null_mut(); }
    };
    let spec = sc_image::ThumbnailSpec { width: thumb_size, height: thumb_size };
    let thumb = sc_image::thumbnail::generate_thumbnail(&img, spec).to_rgba8();
    *out_width = thumb.width();
    *out_height = thumb.height();
    let rgba: Vec<u8> = thumb.into_raw();
    let boxed: Box<[u8]> = rgba.into_boxed_slice();
    *out_len = boxed.len();
    set_err(0);
    Box::into_raw(boxed) as *mut u8
}

/// C-callable: cap image bytes to a maximum dimension using Rust Lanczos3 scaling.
///
/// If max(original_width, original_height) > `max_dim`, scales the image down
/// so the longest side equals `max_dim` (aspect-ratio preserved).
/// If the image already fits within `max_dim`, returns NULL and sets
/// `*error_code_out` to 0 — the caller should use the original bytes unchanged.
///
/// On scale: returns heap-allocated RGBA buffer; writes dimensions to
/// `*out_width`/`*out_height` and byte count to `*out_len`.
/// Caller releases with `sc_free_bytes(ptr, *out_len)`.
/// On failure: returns NULL and sets `*error_code_out` to 1.
/// No-scaling case: returns NULL and sets `*error_code_out` to 0.
///
/// # Safety
/// `image_bytes` must point to `image_len` valid bytes.
/// `out_len`, `out_width`, `out_height` must be valid non-null pointers.
/// `error_code_out` may be null.
#[no_mangle]
pub unsafe extern "C" fn sc_cap_image_bytes(
    image_bytes: *const u8,
    image_len: usize,
    max_dim: u32,
    out_len: *mut usize,
    out_width: *mut u32,
    out_height: *mut u32,
    error_code_out: *mut i32,
) -> *mut u8 {
    let set_err = |code: i32| {
        if !error_code_out.is_null() {
            *error_code_out = code;
        }
    };
    if image_bytes.is_null() || out_len.is_null() || out_width.is_null() || out_height.is_null() {
        set_err(1);
        return std::ptr::null_mut();
    }
    let bytes = std::slice::from_raw_parts(image_bytes, image_len);
    let img = match image::load_from_memory(bytes) {
        Ok(i) => i,
        Err(_) => { set_err(1); return std::ptr::null_mut(); }
    };
    let max_side = img.width().max(img.height());
    if max_side <= max_dim {
        // Already within bounds — no scaling needed.
        set_err(0);
        return std::ptr::null_mut();
    }
    let spec = sc_image::ThumbnailSpec { width: max_dim, height: max_dim };
    let scaled = sc_image::thumbnail::generate_thumbnail(&img, spec).to_rgba8();
    *out_width = scaled.width();
    *out_height = scaled.height();
    let boxed: Box<[u8]> = scaled.into_raw().into_boxed_slice();
    *out_len = boxed.len();
    set_err(0);
    Box::into_raw(boxed) as *mut u8
}

// ── Thumbnail functions ───────────────────────────────────────────────────────

/// Generate a thumbnail for raw image bytes. Returns raw RGBA bytes.
pub fn generate_thumbnail(image_bytes: &[u8], thumb_size: u32) -> Result<Vec<u8>, ScError> {
    let img = image::load_from_memory(image_bytes).map_err(|_| ScError::Image)?;
    let spec = sc_image::ThumbnailSpec {
        width: thumb_size,
        height: thumb_size,
    };
    let thumb = sc_image::thumbnail::generate_thumbnail(&img, spec);
    Ok(thumb.to_rgba8().into_raw())
}

/// Generate thumbnails for all pages in an archive in parallel.
pub fn generate_archive_thumbnails(
    archive_path: &str,
    thumb_size: u32,
) -> Result<Vec<ThumbnailRecord>, ScError> {
    let mut archive =
        sc_archive::open_archive(std::path::Path::new(archive_path)).map_err(ScError::from)?;

    let entries: Vec<(usize, Vec<u8>)> = archive
        .entries()
        .iter()
        .map(|e| e.index)
        .collect::<Vec<_>>()
        .into_iter()
        .filter_map(|idx| archive.read_entry(idx).ok().map(|b| (idx, b)))
        .collect();

    let spec = sc_image::ThumbnailSpec {
        width: thumb_size,
        height: thumb_size,
    };
    let thumbnails = sc_image::generate_thumbnails_sorted(&entries, spec);

    Ok(thumbnails
        .into_iter()
        .map(|(idx, img)| {
            let rgba = img.to_rgba8();
            ThumbnailRecord {
                index: idx as u32,
                rgba_bytes: rgba.clone().into_raw(),
                width: rgba.width(),
                height: rgba.height(),
            }
        })
        .collect())
}

// ── Type conversions ──────────────────────────────────────────────────────────

fn state_to_record(s: sc_storage::SessionState) -> SessionStateRecord {
    use sc_core::types::{PageOrder, Rotation, ScaleMode};
    SessionStateRecord {
        page_index: s.page_index as u32,
        zoom_level: s.zoom_level,
        rotation_degrees: match s.rotation {
            Rotation::R0 => 0,
            Rotation::R90 => 90,
            Rotation::R180 => 180,
            Rotation::R270 => 270,
        },
        two_page_spread: s.two_page_spread,
        right_to_left: matches!(s.page_order, PageOrder::RightToLeft),
        scale_mode: match s.scale_mode {
            ScaleMode::Original => 0,
            ScaleMode::FitWindow => 1,
            ScaleMode::FitWidth => 2,
        },
        scroll_x: s.scroll_x,
        scroll_y: s.scroll_y,
    }
}

fn record_to_state(r: SessionStateRecord) -> sc_storage::SessionState {
    use sc_core::types::{PageOrder, Rotation, ScaleMode};
    sc_storage::SessionState {
        page_index: r.page_index as usize,
        zoom_level: r.zoom_level,
        rotation: match r.rotation_degrees {
            90 => Rotation::R90,
            180 => Rotation::R180,
            270 => Rotation::R270,
            _ => Rotation::R0,
        },
        two_page_spread: r.two_page_spread,
        page_order: if r.right_to_left {
            PageOrder::RightToLeft
        } else {
            PageOrder::LeftToRight
        },
        scale_mode: match r.scale_mode {
            0 => ScaleMode::Original,
            2 => ScaleMode::FitWidth,
            _ => ScaleMode::FitWindow,
        },
        scroll_x: r.scroll_x,
        scroll_y: r.scroll_y,
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sc_version_nonnull() {
        assert!(!sc_version().is_null());
    }

    #[test]
    fn sc_library_version_semver() {
        let v = sc_library_version();
        assert_eq!(v.split('.').count(), 3, "expected SemVer, got {v}");
    }

    #[test]
    fn archive_list_pages_missing_err() {
        assert!(archive_list_pages("/no/such.cbz").is_err());
    }

    #[test]
    fn archive_read_first_image_missing_err() {
        assert!(archive_read_first_image("/no/such.cbz").is_err());
    }

    #[test]
    fn archive_read_page_missing_err() {
        assert!(archive_read_page("/no/such.cbz", 0).is_err());
    }

    #[test]
    fn session_load_missing_returns_default() {
        let s = session_load("/nonexistent_sc_test.cbz").expect("should return default");
        assert_eq!(s.page_index, 0);
        assert!(!s.two_page_spread);
    }

    #[test]
    fn session_delete_noop_on_missing() {
        // Must not panic; returns ()
        session_delete("/nonexistent_sc_test.cbz");
    }

    // ── sc_archive_read_page C FFI tests ─────────────────────────────────────

    fn make_test_cbz(page_count: usize) -> tempfile::NamedTempFile {
        use std::io::Write as _;
        const MINIMAL_PNG: &[u8] = &[
            0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A,
            0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52,
            0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01,
            0x08, 0x02, 0x00, 0x00, 0x00, 0x90, 0x77, 0x53,
            0xDE, 0x00, 0x00, 0x00, 0x0C, 0x49, 0x44, 0x41,
            0x54, 0x78, 0x9C, 0x63, 0xF8, 0xCF, 0xC0, 0x00,
            0x00, 0x03, 0x01, 0x01, 0x00, 0xC9, 0xFE, 0x92,
            0xEF, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E,
            0x44, 0xAE, 0x42, 0x60, 0x82,
        ];
        let tmp = tempfile::Builder::new()
            .suffix(".cbz")
            .tempfile()
            .expect("tempfile");
        let file = tmp.reopen().expect("reopen");
        let mut zip = zip::ZipWriter::new(file);
        let opts = zip::write::SimpleFileOptions::default()
            .compression_method(zip::CompressionMethod::Stored);
        for i in 1..=page_count {
            zip.start_file(format!("page{i:03}.png"), opts).expect("start_file");
            zip.write_all(MINIMAL_PNG).expect("write_all");
        }
        zip.finish().expect("finish");
        tmp
    }

    #[test]
    fn c_ffi_read_page_success() {
        let tmp = make_test_cbz(3);
        let path = std::ffi::CString::new(tmp.path().to_str().unwrap()).unwrap();
        let mut out_len: usize = 0;
        let mut err_code: i32 = -1;
        let ptr = unsafe { sc_archive_read_page(path.as_ptr(), 0, &mut out_len, &mut err_code) };
        assert!(!ptr.is_null(), "expected non-null buffer");
        assert!(out_len > 0, "expected non-zero length");
        assert_eq!(err_code, 0);
        unsafe { sc_free_bytes(ptr, out_len) };
    }

    #[test]
    fn c_ffi_read_page_out_of_range() {
        let tmp = make_test_cbz(3);
        let path = std::ffi::CString::new(tmp.path().to_str().unwrap()).unwrap();
        let mut out_len: usize = 0;
        let mut err_code: i32 = 0;
        let ptr = unsafe { sc_archive_read_page(path.as_ptr(), 999, &mut out_len, &mut err_code) };
        assert!(ptr.is_null());
        assert_eq!(err_code, 2);
    }

    #[test]
    fn c_ffi_read_page_null_path() {
        let mut out_len: usize = 0;
        let mut err_code: i32 = 0;
        let ptr = unsafe {
            sc_archive_read_page(std::ptr::null(), 0, &mut out_len, &mut err_code)
        };
        assert!(ptr.is_null());
        assert_eq!(err_code, 1);
    }

    #[test]
    fn c_ffi_free_bytes_null_safe() {
        // Must not panic or crash
        unsafe { sc_free_bytes(std::ptr::null_mut(), 0) };
    }

    // ── ScPageList C FFI tests ────────────────────────────────────────────────

    #[test]
    fn page_list_open_and_enumerate() {
        let tmp = make_test_cbz(3);
        let path = std::ffi::CString::new(tmp.path().to_str().unwrap()).unwrap();
        let mut err: i32 = -1;
        let list = unsafe { sc_archive_open_pages(path.as_ptr(), &mut err) };
        assert!(!list.is_null(), "expected non-null ScPageList");
        assert_eq!(err, 0);
        let count = unsafe { sc_page_list_count(list) };
        assert_eq!(count, 3);
        for i in 0..count {
            let name_ptr = unsafe { sc_page_list_name(list, i) };
            assert!(!name_ptr.is_null());
            let name = unsafe { std::ffi::CStr::from_ptr(name_ptr) }
                .to_str()
                .expect("valid UTF-8");
            assert!(name.ends_with(".png"), "expected .png, got {name}");
        }
        unsafe { sc_archive_pages_free(list) };
    }

    #[test]
    fn page_list_null_path_returns_null() {
        let mut err: i32 = 0;
        let list = unsafe { sc_archive_open_pages(std::ptr::null(), &mut err) };
        assert!(list.is_null());
        assert_eq!(err, 1);
    }

    #[test]
    fn page_list_missing_archive_returns_null() {
        let path = std::ffi::CString::new("/no/such/archive.cbz").unwrap();
        let mut err: i32 = 0;
        let list = unsafe { sc_archive_open_pages(path.as_ptr(), &mut err) };
        assert!(list.is_null());
        assert!(err != 0);
    }

    #[test]
    fn page_list_out_of_range_returns_null() {
        let tmp = make_test_cbz(2);
        let path = std::ffi::CString::new(tmp.path().to_str().unwrap()).unwrap();
        let list = unsafe { sc_archive_open_pages(path.as_ptr(), std::ptr::null_mut()) };
        assert!(!list.is_null());
        assert_eq!(unsafe { sc_page_list_count(list) }, 2);
        let bad_name = unsafe { sc_page_list_name(list, 999) };
        assert!(bad_name.is_null());
        let bad_size = unsafe { sc_page_list_size(list, 999) };
        assert_eq!(bad_size, 0);
        unsafe { sc_archive_pages_free(list) };
    }

    #[test]
    fn page_list_free_null_safe() {
        unsafe { sc_archive_pages_free(std::ptr::null_mut()) };
    }

    // ── ScSessionState C FFI tests ────────────────────────────────────────────

    #[test]
    fn c_session_load_returns_false_for_missing() {
        // sc_session_load returns false (and does NOT write out_state) when the path
        // has no record in the DB.  This lets ObjC callers detect "no saved session".
        let path = std::ffi::CString::new("/nonexistent_sprint14_test.cbz").unwrap();
        let mut state = ScSessionState {
            page_index: 99, zoom_level: 0.0, rotation_degrees: 0,
            two_page_spread: true, right_to_left: false, scale_mode: 0,
            scroll_x: 0.0, scroll_y: 0.0,
        };
        let ok = unsafe { sc_session_load(path.as_ptr(), &mut state) };
        assert!(!ok, "sc_session_load should return false for missing archive");
        // out_state is not written when returning false — page_index stays at 99
        assert_eq!(state.page_index, 99, "out_state should not be touched on false return");
    }

    #[test]
    fn c_session_save_does_not_crash() {
        // Tests use an in-memory DB (per open_session_db cfg(test)), so save succeeds
        // but the data is not visible to a subsequent load call (different connection).
        // Full roundtrip persistence is tested by the uniffi session_load/session_save tests.
        let path = std::ffi::CString::new("/tmp/sc_sprint14_save_test.cbz").unwrap();
        let state = ScSessionState {
            page_index: 7, zoom_level: 1.5, rotation_degrees: 90,
            two_page_spread: true, right_to_left: true, scale_mode: 2,
            scroll_x: 10.0, scroll_y: 20.0,
        };
        let saved = unsafe { sc_session_save(path.as_ptr(), &state) };
        assert!(saved, "sc_session_save should not crash and should return true");
    }

    #[test]
    fn c_session_load_null_path_returns_false() {
        let mut state = ScSessionState {
            page_index: 0, zoom_level: 1.0, rotation_degrees: 0,
            two_page_spread: false, right_to_left: false, scale_mode: 0,
            scroll_x: 0.0, scroll_y: 0.0,
        };
        let ok = unsafe { sc_session_load(std::ptr::null(), &mut state) };
        assert!(!ok);
    }

    #[test]
    fn c_session_delete_null_safe() {
        unsafe { sc_session_delete_c(std::ptr::null()) };
    }

    // ── sc_cap_image_bytes tests ──────────────────────────────────────────────

    #[test]
    fn cap_image_no_scale_when_small() {
        // 1×1 PNG is 1 pixel — well below any max_dim; should return NULL, errCode=0
        let tmp = make_test_cbz(1);
        let path = std::ffi::CString::new(tmp.path().to_str().unwrap()).unwrap();
        let mut out_len: usize = 0; let mut err: i32 = -1;
        // Read first page raw bytes
        let page_bytes = archive_read_page(tmp.path().to_str().unwrap(), 0)
            .expect("read page");
        let mut out_w: u32 = 0; let mut out_h: u32 = 0;
        let ptr = unsafe {
            sc_cap_image_bytes(page_bytes.as_ptr(), page_bytes.len(), 2048,
                               &mut out_len, &mut out_w, &mut out_h, &mut err)
        };
        // 1×1 image < 2048 → should return NULL (no scaling needed)
        assert!(ptr.is_null(), "small image should not be scaled");
        assert_eq!(err, 0, "error code should be 0 (not an error, just no-op)");
        let _ = path; // keep tmp alive
    }

    #[test]
    fn cap_image_null_path_returns_null() {
        let mut out_len: usize = 0; let mut out_w: u32 = 0; let mut out_h: u32 = 0;
        let mut err: i32 = 0;
        let ptr = unsafe {
            sc_cap_image_bytes(std::ptr::null(), 0, 2048, &mut out_len, &mut out_w, &mut out_h, &mut err)
        };
        assert!(ptr.is_null());
        assert_eq!(err, 1);
    }
}
