// uniffi scaffolding generated from src/simplecomic.udl
uniffi::include_scaffolding!("simplecomic");

use thiserror::Error;

// ── Record types (UDL `dictionary` mapping) ───────────────────────────────────

// In the UDL workflow, scaffolding generated by build.rs already applies the
// udl_derive(Record) attribute; adding #[derive(uniffi::Record)] here would
// duplicate trait impls and cause E0119.  Plain derives only.
#[derive(Debug, Clone)]
pub struct ArchiveEntryRecord {
    pub index: u32,
    pub filename: String,
    pub size_bytes: u64,
}

#[derive(Debug, Clone)]
pub struct SessionStateRecord {
    pub page_index: u32,
    pub zoom_level: f64,
    pub rotation_degrees: i32,
    pub two_page_spread: bool,
    pub right_to_left: bool,
    pub scale_mode: i32,
    pub scroll_x: f64,
    pub scroll_y: f64,
}

#[derive(Debug, Clone)]
pub struct ThumbnailRecord {
    pub index: u32,
    pub rgba_bytes: Vec<u8>,
    pub width: u32,
    pub height: u32,
}

// ── Error type (UDL `[Error] enum` mapping) ──────────────────────────────────
// Flat enum: no associated data on any variant; uniffi exposes the Display
// message as the Swift error description.
// The udl_derive(Error) attribute is applied by the scaffolding; no
// #[derive(uniffi::Error)] needed here.

#[derive(Debug, Error)]
pub enum ScError {
    #[error("archive error")]
    Archive,
    #[error("image error")]
    Image,
    #[error("storage error")]
    Storage,
    #[error("I/O error")]
    Io,
    #[error("unsupported format")]
    UnsupportedFormat,
    #[error("entry not found")]
    EntryNotFound,
}

impl From<anyhow::Error> for ScError {
    fn from(e: anyhow::Error) -> Self {
        let msg = e.to_string();
        if msg.contains("unsupported format") || msg.contains("unknown magic") {
            ScError::UnsupportedFormat
        } else if msg.contains("not found")
            || msg.contains("out of range")
            || msg.contains("no image")
        {
            ScError::EntryNotFound
        } else {
            ScError::Archive
        }
    }
}

// ── C smoke-test export ───────────────────────────────────────────────────────

/// Returns the library version as a C string.
///
/// # Safety
///
/// The returned pointer is valid for the lifetime of the process; callers must
/// not free it.
#[no_mangle]
pub extern "C" fn sc_version() -> *const std::ffi::c_char {
    c"0.1.0".as_ptr()
}

// ── Archive namespace functions (UDL `namespace simplecomic`) ─────────────────

pub fn archive_is_supported(archive_path: &str) -> bool {
    sc_archive::is_archive_supported(std::path::Path::new(archive_path))
}

/// C-callable: returns true if the NUL-terminated UTF-8 `path` is a supported archive.
///
/// # Safety
/// `path` must be a valid NUL-terminated C string. Null pointer returns false.
#[no_mangle]
pub unsafe extern "C" fn sc_archive_is_supported(path: *const std::ffi::c_char) -> bool {
    if path.is_null() {
        return false;
    }
    let cstr = unsafe { std::ffi::CStr::from_ptr(path) };
    let s = match cstr.to_str() {
        Ok(s) => s,
        Err(_) => return false,
    };
    sc_archive::is_archive_supported(std::path::Path::new(s))
}

pub fn archive_list_pages(archive_path: &str) -> Result<Vec<ArchiveEntryRecord>, ScError> {
    let archive =
        sc_archive::open_archive(std::path::Path::new(archive_path)).map_err(ScError::from)?;
    let entries = archive
        .entries()
        .iter()
        .map(|e| ArchiveEntryRecord {
            index: e.index as u32,
            filename: e.filename.clone(),
            size_bytes: e.size,
        })
        .collect();
    Ok(entries)
}

pub fn archive_read_page(archive_path: &str, index: u32) -> Result<Vec<u8>, ScError> {
    let mut archive =
        sc_archive::open_archive(std::path::Path::new(archive_path)).map_err(ScError::from)?;
    let page_count = archive.entries().len();
    let idx = index as usize;
    if idx >= page_count {
        return Err(ScError::EntryNotFound);
    }
    archive.read_entry(idx).map_err(ScError::from)
}

pub fn archive_read_first_image(archive_path: &str) -> Result<Vec<u8>, ScError> {
    sc_archive::read_first_image(std::path::Path::new(archive_path)).map_err(ScError::from)
}

// ── Session namespace functions ───────────────────────────────────────────────

/// Open the session database.
///
/// In test builds uses an in-memory database so parallel tests do not contend
/// on the same file.  In production uses a file under the platform app-support directory:
/// - macOS: ~/Library/Application Support/SimpleComic/sessions.sqlite
/// - Linux: ~/.local/share/SimpleComic/sessions.sqlite
/// - Fallback: $TMPDIR/simplecomic_sessions.sqlite
#[cfg(not(test))]
fn open_session_db() -> Result<sc_storage::SessionManager, ScError> {
    let base = dirs::data_dir()
        .or_else(|| dirs::home_dir().map(|h| h.join(".local/share")))
        .unwrap_or_else(std::env::temp_dir);

    let app_dir = base.join("SimpleComic");
    if !app_dir.exists() {
        let _ = std::fs::create_dir_all(&app_dir);
    }

    let db_path = app_dir.join("sessions.sqlite");
    sc_storage::SessionManager::open(&db_path).map_err(|_| ScError::Storage)
}

#[cfg(test)]
fn open_session_db() -> Result<sc_storage::SessionManager, ScError> {
    sc_storage::SessionManager::open_in_memory().map_err(|_| ScError::Storage)
}

pub fn session_load(archive_path: &str) -> Result<SessionStateRecord, ScError> {
    let mgr = open_session_db()?;
    let state = mgr.load(archive_path).map_err(|_| ScError::Storage)?;
    Ok(state_to_record(state))
}

// UDL: void session_save([ByRef] string archive_path, SessionStateRecord state)
// → no [Throws] suppression: this function IS [Throws=ScError] in UDL, Result is correct.
pub fn session_save(archive_path: &str, state: SessionStateRecord) -> Result<(), ScError> {
    let mgr = open_session_db()?;
    mgr.save(archive_path, &record_to_state(state))
        .map_err(|_| ScError::Storage)
}

// UDL: void session_delete([ByRef] string archive_path)   — no [Throws], returns ()
pub fn session_delete(archive_path: &str) {
    if let Ok(mgr) = open_session_db() {
        let _ = mgr.delete(archive_path);
    }
}

pub fn sc_library_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

// ── Thumbnail functions ───────────────────────────────────────────────────────

/// Generate a thumbnail for raw image bytes. Returns raw RGBA bytes.
pub fn generate_thumbnail(image_bytes: &[u8], thumb_size: u32) -> Result<Vec<u8>, ScError> {
    let img = image::load_from_memory(image_bytes).map_err(|_| ScError::Image)?;
    let spec = sc_image::ThumbnailSpec {
        width: thumb_size,
        height: thumb_size,
    };
    let thumb = sc_image::thumbnail::generate_thumbnail(&img, spec);
    Ok(thumb.to_rgba8().into_raw())
}

/// Generate thumbnails for all pages in an archive in parallel.
pub fn generate_archive_thumbnails(
    archive_path: &str,
    thumb_size: u32,
) -> Result<Vec<ThumbnailRecord>, ScError> {
    let mut archive =
        sc_archive::open_archive(std::path::Path::new(archive_path)).map_err(ScError::from)?;

    let entries: Vec<(usize, Vec<u8>)> = archive
        .entries()
        .iter()
        .map(|e| e.index)
        .collect::<Vec<_>>()
        .into_iter()
        .filter_map(|idx| archive.read_entry(idx).ok().map(|b| (idx, b)))
        .collect();

    let spec = sc_image::ThumbnailSpec {
        width: thumb_size,
        height: thumb_size,
    };
    let thumbnails = sc_image::generate_thumbnails_sorted(&entries, spec);

    Ok(thumbnails
        .into_iter()
        .map(|(idx, img)| {
            let rgba = img.to_rgba8();
            ThumbnailRecord {
                index: idx as u32,
                rgba_bytes: rgba.clone().into_raw(),
                width: rgba.width(),
                height: rgba.height(),
            }
        })
        .collect())
}

// ── Type conversions ──────────────────────────────────────────────────────────

fn state_to_record(s: sc_storage::SessionState) -> SessionStateRecord {
    use sc_core::types::{PageOrder, Rotation, ScaleMode};
    SessionStateRecord {
        page_index: s.page_index as u32,
        zoom_level: s.zoom_level,
        rotation_degrees: match s.rotation {
            Rotation::R0 => 0,
            Rotation::R90 => 90,
            Rotation::R180 => 180,
            Rotation::R270 => 270,
        },
        two_page_spread: s.two_page_spread,
        right_to_left: matches!(s.page_order, PageOrder::RightToLeft),
        scale_mode: match s.scale_mode {
            ScaleMode::Original => 0,
            ScaleMode::FitWindow => 1,
            ScaleMode::FitWidth => 2,
        },
        scroll_x: s.scroll_x,
        scroll_y: s.scroll_y,
    }
}

fn record_to_state(r: SessionStateRecord) -> sc_storage::SessionState {
    use sc_core::types::{PageOrder, Rotation, ScaleMode};
    sc_storage::SessionState {
        page_index: r.page_index as usize,
        zoom_level: r.zoom_level,
        rotation: match r.rotation_degrees {
            90 => Rotation::R90,
            180 => Rotation::R180,
            270 => Rotation::R270,
            _ => Rotation::R0,
        },
        two_page_spread: r.two_page_spread,
        page_order: if r.right_to_left {
            PageOrder::RightToLeft
        } else {
            PageOrder::LeftToRight
        },
        scale_mode: match r.scale_mode {
            0 => ScaleMode::Original,
            2 => ScaleMode::FitWidth,
            _ => ScaleMode::FitWindow,
        },
        scroll_x: r.scroll_x,
        scroll_y: r.scroll_y,
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sc_version_nonnull() {
        assert!(!sc_version().is_null());
    }

    #[test]
    fn sc_library_version_semver() {
        let v = sc_library_version();
        assert_eq!(v.split('.').count(), 3, "expected SemVer, got {v}");
    }

    #[test]
    fn archive_list_pages_missing_err() {
        assert!(archive_list_pages("/no/such.cbz").is_err());
    }

    #[test]
    fn archive_read_first_image_missing_err() {
        assert!(archive_read_first_image("/no/such.cbz").is_err());
    }

    #[test]
    fn archive_read_page_missing_err() {
        assert!(archive_read_page("/no/such.cbz", 0).is_err());
    }

    #[test]
    fn session_load_missing_returns_default() {
        let s = session_load("/nonexistent_sc_test.cbz").expect("should return default");
        assert_eq!(s.page_index, 0);
        assert!(!s.two_page_spread);
    }

    #[test]
    fn session_delete_noop_on_missing() {
        // Must not panic; returns ()
        session_delete("/nonexistent_sc_test.cbz");
    }
}
